version: '3.2'
services:
  frontend:
    image: 'ruby:2.7'
    volumes:
      # - pyroscope_bin7:/tmp/pyroscope-bin
      - '.:/app/src'
    command:
      - /bin/bash
      - -c
      - |
        unset http_proxy https_proxy HTTP_PROXY HTTPS_PROXY no_proxy
        cd /app/src
        gem install bundler
        bundle update --bundler
        bundle install
        ruby services/frontend/server.rb
    ports:
      - "8080:80"
    environment:
      - USE_DOCKER_COMPOSE=1
  customer:
    image: 'ruby:2.7'
    volumes:
      # - pyroscope_bin7:/tmp/pyroscope-bin
      - '.:/app/src'
    command:
      - /bin/bash
      - -c
      - |
        unset http_proxy https_proxy HTTP_PROXY HTTPS_PROXY no_proxy
        cd /app/src
        gem install bundler
        bundle update --bundler
        bundle install
        ruby services/customer/server.rb
    ports:
      - "8081:80"
    environment:
      - USE_DOCKER_COMPOSE=1
  driver:
    image: 'ruby:2.7'
    volumes:
      # - pyroscope_bin7:/tmp/pyroscope-bin
      - '.:/app/src'
    command:
      - /bin/bash
      - -c
      - |
        unset http_proxy https_proxy HTTP_PROXY HTTPS_PROXY no_proxy
        cd /app/src
        gem install bundler
        bundle update --bundler
        bundle install
        ruby services/driver/server.rb
    ports:
      - "8082:80"
    environment:
      - USE_DOCKER_COMPOSE=1
  route:
    image: 'ruby:2.7'
    volumes:
      # - pyroscope_bin7:/tmp/pyroscope-bin
      - '.:/app/src'
    command:
      - /bin/bash
      - -c
      - |
        unset http_proxy https_proxy HTTP_PROXY HTTPS_PROXY no_proxy
        cd /app/src
        gem install bundler
        bundle update --bundler
        bundle install
        ruby services/route/server.rb
    ports:
      - "8083:80"
    environment:
      - USE_DOCKER_COMPOSE=1
