version: '3.2'

services:
  pyroscope:
    image: 'pyroscope/pyroscope:dev'
    volumes:
      - /Users/dmitry/Dev/ps/pyroscope/tmp/pyroscope-storage:/var/lib/pyroscope
    command:
      - server
    ports:
      - "9090:8080"
  frontend:
    image: 'pyroscope/hotrod-ruby:dev'
    # entrypoint:
    #   - /usr/local/bin/ruby
    platform: linux/amd64
    command:
      - services/frontend/server.rb
    ports:
      - "8080:80"
    cap_add:
      - SYS_PTRACE
    environment:
      - USE_DOCKER_COMPOSE=1
      - PYROSCOPE_SPY_NAME=rbspy
      - PYROSCOPE_APPLICATION_NAME=hotrod.ruby.frontend
      - PYROSCOPE_SERVER_ADDRESS=http://pyroscope:8080/
  customer:
    image: 'pyroscope/hotrod-ruby:dev'
    # entrypoint:
    #   - /usr/local/bin/ruby
    platform: linux/amd64
    command:
      - services/customer/server.rb
    ports:
      - "8081:80"
    cap_add:
      - SYS_PTRACE
    environment:
      - USE_DOCKER_COMPOSE=1
      - PYROSCOPE_SPY_NAME=rbspy
      - PYROSCOPE_APPLICATION_NAME=hotrod.ruby.frontend
      - PYROSCOPE_SERVER_ADDRESS=http://pyroscope:8080/
  driver:
    image: 'pyroscope/hotrod-ruby:dev'
    # entrypoint:
    #   - /usr/local/bin/ruby
    platform: linux/amd64
    command:
      - services/driver/server.rb
    ports:
      - "8082:80"
    cap_add:
      - SYS_PTRACE
    environment:
      - USE_DOCKER_COMPOSE=1
      - PYROSCOPE_SPY_NAME=rbspy
      - PYROSCOPE_APPLICATION_NAME=hotrod.ruby.frontend
      - PYROSCOPE_SERVER_ADDRESS=http://pyroscope:8080/
  route:
    image: 'pyroscope/hotrod-ruby:dev'
    # entrypoint:
    #   - /usr/local/bin/ruby
    platform: linux/amd64
    command:
      - services/route/server.rb
    ports:
      - "8083:80"
    cap_add:
      - SYS_PTRACE
    environment:
      - USE_DOCKER_COMPOSE=1
      - PYROSCOPE_SPY_NAME=rbspy
      - PYROSCOPE_APPLICATION_NAME=hotrod.ruby.frontend
      - PYROSCOPE_SERVER_ADDRESS=http://pyroscope:8080/
